# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-marielle'
    organization: 'mtnolasco1'
    scannerMode: 'MSBuild'
    projectKey: 'webdemonolasco'
    projectName: 'webdemonolasco'
    extraProperties: |
      sonar.exclusions = **/lib/**

- script: cd Project1WebApp && dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# - script: dotnet test
#   displayName: dotnet test
#   workingDirectory: Project1WebApp
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './Project1WebApp'
    arguments: '-c $(buildConfiguration) --collect "XPlat Code Coverage"'

- task: SonarCloudAnalyze@1
  displayName: Run code analysis

- task: SonarCloudPublish@1
  displayName: publish code analysis
  
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: app service deploy
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
- task: AzureRmWebAppDeployment@4
  displayName: dotnet publish + zip
  inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(cb0d2e9c-c632-4eec-93d0-d1e5f9589605)'
      appType: 'webApp'
      WebAppName: 'WeBDemoNolasco'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

