DROP TABLE Inventory
DROP TABLE CustOrder
DROP TABLE Orders
DROP TABLE Customer
DROP TABLE Location
DROP TABLE Product

CREATE TABLE Customer (
	CustID INT NOT NULL PRIMARY KEY IDENTITY (1000, 1),
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	Street NVARCHAR(20) NOT NULL,
	City NVARCHAR(20) NOT NULL,
	State NVARCHAR(20) NOT NULL,
	ZipCode NVARCHAR(20) NOT NULL
);

CREATE TABLE Location(
	LocationID INT NOT NULL PRIMARY KEY IDENTITY(1000, 1),
	BranchName NVARCHAR(50) NOT NULL,
	Street NVARCHAR(20) NOT NULL,
	City NVARCHAR(20) NOT NULL,
	State NVARCHAR(20) NOT NULL,
	ZipCode NVARCHAR(20) NOT NULL
);

CREATE TABLE Orders (
	OrderID INT NOT NULL PRIMARY KEY IDENTITY (1000, 1),
	Total MONEY NOT NULL,
	CustID INT FOREIGN KEY REFERENCES Customer(CustID),
	LocationID INT FOREIGN KEY REFERENCES Location(LocationID),
	OrderDate DATETIME NOT NULL
);

CREATE TABLE Product(
	ProductID INT NOT NULL PRIMARY KEY IDENTITY(1000,1),
	Name NVARCHAR(50) NOT NULL,
	Price MONEY NOT NULL
);

CREATE TABLE Inventory(
	InventoryID INT NOT NULL PRIMARY KEY IDENTITY(1000, 1),
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ProductID),
	Stock INT NOT NULL,
	LocationID INT FOREIGN KEY REFERENCES Location(LocationID)
);

CREATE TABLE CustOrder(
	CustOrderID INT NOT NULL PRIMARY KEY IDENTITY(1000,1),
	OrderID INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderID),
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ProductID),
	Quantity INT NOT NULL
);